### ISSUE TITLE
Add tests for Resources and Endpoints

### ISSUE THREAD

**Issue by excid3** [excid3/vultr.rb#3]
We need tests added for each of the Resources in the Vultr API. The full list is here: https://www.vultr.com/api

- [x] Account
- [x] Applications
- [x] Backups
- [x] Bare Metal
- [x] Block Storage
- [x] DNS
- [x] Firewall
- [x] Instances
- [x] ISO
- [x] Kubernetes
- [x] Load Balancers
- [x] Object Storage
- [x] Operating Systems
- [x] Plans
- [x] Private Networks
- [x] Regions
- [x] Reserved IPs
- [x] Snapshots
- [x] SSH Keys
- [x] Startup Scripts
- [x] Users

You can use `test/vultr/resources/users_test.rb` as a reference. It has tests for CRUD and you can copy this as a starting place.

The API docs have example response JSON that should be added into `test/fixtures` (see `test/fixtures/users/` for example .json fixtures from the docs).

**Comment by stevepolitodesign** [comment]
@excid3 put me in Coach.

**Comment by excid3** [comment]
You got it! I'll leave it up to you to decide if you want to make separate PRs for each resource or go with the grand slam and do it all together.

**Comment by excid3** [comment]
@leoanthonyc knocked out Startup Scripts (and fixed a bug!). 🙏

**Comment by stevepolitodesign** [comment]
@excid3 I'll tackle the [Applications](https://www.vultr.com/api/#tag/application) resource.

**Comment by stevepolitodesign** [comment]
@excid3 I can also tackle [Backups](https://www.vultr.com/api/#tag/backup).

**Comment by excid3** [comment]
You got it. 👍

**Comment by JuanVqz** [comment]
@excid3 I did **Plans** #15

**Comment by excid3** [comment]
Thank you @JuanVqz 💪💪

**Comment by JuanVqz** [comment]
I'll tackle DNS, please.

**Comment by excid3** [comment]
Making great progress. Thanks for the help everyone!

**Comment by JuanVqz** [comment]
I'm doing ISO

**Comment by excid3** [comment]
Okay! The list is almost finished!! 🔥

**Comment by excid3** [comment]
Huge shoutout to @gordysc for Block Storage and K8s!

**Comment by JuanVqz** [comment]
thank you @excid3 for allowing us to contribute!

**Comment by excid3** [comment]
Thanks for your help @JuanVqz 🙏
